### ISSUE TITLE
mobile version menu not accessible from home page

### ISSUE THREAD

**Issue by plzmsu** [srm-ecology/srm-ecology-website#17]
@billspat - ideas? mobile version of site home page "menu" is not accessible (it overlaps the link for the home page itself so it's not possible to "pull down" the menu).

**Comment by billspat** [comment]
I can try inserting a break but not sure it will work.   eithe make a shorter title is the quickest suggestion here or wait until we can find time to customize the theme to make the font smaller in the style code.  I would start here : https://wowchemy.com/docs/getting-started/customization/

**Comment by billspat** [comment]
fixed using a narrow font in the nav ( https://fonts.google.com/specimen/News+Cycle ) which may not work in all cases but will for most.

**Comment by billspat** [comment]
Note using google fonts  only barely works (on smaller phone size) and does not work on mobile if someone has installed content blockers (ad, cookie filters).    Instead I simply set it for "small" font size which fixes this problem on mobile but the rest of the text is quite small on desktop.    

To set it back to medium fonts, open `config/_default/params.toml` and set `font_size = "M"`

This could be truly fixed by either working with a fully custom theme per the link above or making the title of the website smaller ( e.g. remove "working group" in the title but adding it in the large text on the home page)

**Comment by billspat** [comment]
the small font size is acceptable and fixes this issue
