### ISSUE TITLE
site not updating after various commits

### ISSUE THREAD

**Issue by plzmsu** [srm-ecology/srm-ecology-website#30]
@billspat - any ideas why the recent commits I made for Lala Kounta, Kelsey Roberts, and minor typo fixes are not posting? I can't figure it out.

**Comment by plzmsu** [comment]
not sure what the issue was; it's working after adding small changes at a time.

**Comment by billspat** [comment]
Glad that you got it to work!  

The issue is if there are syntax errors and the site generator on Netlify can't build the site without error , it doesn't update anything .  I've found formatting the dates to be particularly tricky.   It may be that after making some changes, the syntax is fixed and the site renders ok.  

The site is hosted on Netlify, and for the site there is a list of deployments, which is a lot of when you pushed to master and Netlify builds the site with Hugo ( the engine behind blowdown).  I can see a few times there are
errors when the site generator tried to build the site.    

Are you running a test site on your laptop to check that it's working ?   If you are, and it is working for you but not building on Netlify, it could be that the version of Hugo differs.  I don't know the version on Netlify but can add to the readme instructions how to find this.
